-- 插入測試信用卡資料
INSERT INTO cards (id, card_number, cardholder_name, status, created_at, updated_at) VALUES
(1, '4532123456789012', '王小明', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, '5412345678901234', '李小華', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, '3782822463100005', '張大同', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, '6011111111111117', '陳美玲', 'SUSPENDED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, '4111111111111111', '林志明', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- 插入測試商店資料
INSERT INTO merchants (id, merchant_code, merchant_name, category, location, created_at, updated_at) VALUES
(1, 'M001', '全家便利商店', 'RETAIL', '台北市信義區', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'M002', '鼎泰豐餐廳', 'RESTAURANT', '台北市大安區', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 'M003', '誠品書店', 'RETAIL', '台北市信義區', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 'M004', '台北101購物中心', 'RETAIL', '台北市信義區', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 'M005', '中油加油站', 'GAS_STATION', '台北市中山區', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 'M006', '家樂福超市', 'SUPERMARKET', '新北市板橋區', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(7, 'M007', 'PChome線上購物', 'ONLINE_SHOPPING', '線上', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(8, 'M008', '威秀影城', 'ENTERTAINMENT', '台北市信義區', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- 插入測試交易資料
INSERT INTO transactions (id, card_id, merchant_id, amount, status, transaction_time, description, created_at) VALUES
-- 正常交易
(1, 1, 1, 150.00, 'APPROVED', DATEADD('HOUR', -2, CURRENT_TIMESTAMP), '便利商店購物', CURRENT_TIMESTAMP),
(2, 1, 2, 1200.00, 'APPROVED', DATEADD('HOUR', -3, CURRENT_TIMESTAMP), '餐廳用餐', CURRENT_TIMESTAMP),
(3, 2, 3, 850.00, 'APPROVED', DATEADD('HOUR', -5, CURRENT_TIMESTAMP), '書店購書', CURRENT_TIMESTAMP),
(4, 2, 5, 1500.00, 'APPROVED', DATEADD('HOUR', -6, CURRENT_TIMESTAMP), '加油', CURRENT_TIMESTAMP),
(5, 3, 6, 3200.00, 'APPROVED', DATEADD('HOUR', -8, CURRENT_TIMESTAMP), '超市購物', CURRENT_TIMESTAMP),

-- 高額交易（測試異常偵測）
(6, 1, 4, 65000.00, 'APPROVED', DATEADD('HOUR', -1, CURRENT_TIMESTAMP), '購買精品', CURRENT_TIMESTAMP),
(7, 2, 4, 58000.00, 'APPROVED', DATEADD('MINUTE', -30, CURRENT_TIMESTAMP), '購買3C產品', CURRENT_TIMESTAMP),

-- 頻繁交易（測試異常偵測）
(8, 3, 1, 200.00, 'APPROVED', DATEADD('MINUTE', -50, CURRENT_TIMESTAMP), '便利商店', CURRENT_TIMESTAMP),
(9, 3, 1, 180.00, 'APPROVED', DATEADD('MINUTE', -45, CURRENT_TIMESTAMP), '便利商店', CURRENT_TIMESTAMP),
(10, 3, 1, 220.00, 'APPROVED', DATEADD('MINUTE', -40, CURRENT_TIMESTAMP), '便利商店', CURRENT_TIMESTAMP),
(11, 3, 1, 190.00, 'APPROVED', DATEADD('MINUTE', -35, CURRENT_TIMESTAMP), '便利商店', CURRENT_TIMESTAMP),
(12, 3, 1, 210.00, 'APPROVED', DATEADD('MINUTE', -30, CURRENT_TIMESTAMP), '便利商店', CURRENT_TIMESTAMP),
(13, 3, 1, 195.00, 'APPROVED', DATEADD('MINUTE', -25, CURRENT_TIMESTAMP), '便利商店', CURRENT_TIMESTAMP),

-- 可能重複交易（測試異常偵測）
(14, 5, 7, 2999.00, 'APPROVED', DATEADD('MINUTE', -10, CURRENT_TIMESTAMP), '線上購物', CURRENT_TIMESTAMP),
(15, 5, 7, 2999.00, 'APPROVED', DATEADD('MINUTE', -8, CURRENT_TIMESTAMP), '線上購物', CURRENT_TIMESTAMP),

-- 其他交易
(16, 1, 8, 450.00, 'APPROVED', DATEADD('HOUR', -12, CURRENT_TIMESTAMP), '電影票', CURRENT_TIMESTAMP),
(17, 2, 2, 1800.00, 'APPROVED', DATEADD('HOUR', -15, CURRENT_TIMESTAMP), '餐廳用餐', CURRENT_TIMESTAMP),
(18, 3, 3, 650.00, 'APPROVED', DATEADD('HOUR', -18, CURRENT_TIMESTAMP), '書店購書', CURRENT_TIMESTAMP),
(19, 5, 6, 2800.00, 'APPROVED', DATEADD('HOUR', -20, CURRENT_TIMESTAMP), '超市購物', CURRENT_TIMESTAMP),
(20, 1, 5, 1200.00, 'APPROVED', DATEADD('HOUR', -24, CURRENT_TIMESTAMP), '加油', CURRENT_TIMESTAMP);

-- Made with Bob

-- 插入測試警示資料
INSERT INTO transaction_alerts (alert_id, transaction_id, alert_type, severity, detected_at, description, created_at) VALUES
-- 高額交易警示
(1, 6, 'HIGH_AMOUNT', 'CRITICAL', DATEADD('HOUR', -1, CURRENT_TIMESTAMP), '偵測到異常高額交易：NT$ 65,000，超過一般消費模式', CURRENT_TIMESTAMP),
(2, 7, 'HIGH_AMOUNT', 'HIGH', DATEADD('MINUTE', -30, CURRENT_TIMESTAMP), '偵測到高額交易：NT$ 58,000，建議進行額外驗證', CURRENT_TIMESTAMP),

-- 頻繁交易警示
(3, 8, 'FREQUENT_TRANSACTION', 'MEDIUM', DATEADD('MINUTE', -50, CURRENT_TIMESTAMP), '偵測到短時間內多筆交易（1小時內6筆）', CURRENT_TIMESTAMP),
(4, 9, 'FREQUENT_TRANSACTION', 'MEDIUM', DATEADD('MINUTE', -45, CURRENT_TIMESTAMP), '同一卡片在相同商店連續交易', CURRENT_TIMESTAMP),
(5, 10, 'FREQUENT_TRANSACTION', 'HIGH', DATEADD('MINUTE', -40, CURRENT_TIMESTAMP), '異常頻繁交易模式，可能為盜刷', CURRENT_TIMESTAMP),
(6, 11, 'FREQUENT_TRANSACTION', 'HIGH', DATEADD('MINUTE', -35, CURRENT_TIMESTAMP), '持續偵測到頻繁交易行為', CURRENT_TIMESTAMP),
(7, 12, 'FREQUENT_TRANSACTION', 'CRITICAL', DATEADD('MINUTE', -30, CURRENT_TIMESTAMP), '嚴重異常：1小時內5筆以上交易', CURRENT_TIMESTAMP),
(8, 13, 'FREQUENT_TRANSACTION', 'CRITICAL', DATEADD('MINUTE', -25, CURRENT_TIMESTAMP), '建議立即凍結卡片並聯繫持卡人', CURRENT_TIMESTAMP),

-- 重複交易警示
(9, 14, 'DUPLICATE_TRANSACTION', 'MEDIUM', DATEADD('MINUTE', -10, CURRENT_TIMESTAMP), '偵測到可能的重複交易：相同金額 NT$ 2,999', CURRENT_TIMESTAMP),
(10, 15, 'DUPLICATE_TRANSACTION', 'HIGH', DATEADD('MINUTE', -8, CURRENT_TIMESTAMP), '確認重複交易：2分鐘內相同商店相同金額', CURRENT_TIMESTAMP),

-- 異常時間交易警示
(11, 5, 'UNUSUAL_TIME', 'LOW', DATEADD('HOUR', -8, CURRENT_TIMESTAMP), '深夜時段大額超市消費，與平常消費習慣不符', CURRENT_TIMESTAMP),

-- 可疑地點警示
(12, 7, 'SUSPICIOUS_LOCATION', 'MEDIUM', DATEADD('MINUTE', -30, CURRENT_TIMESTAMP), '交易地點與持卡人常用地點差異較大', CURRENT_TIMESTAMP);

-- Made with Bob
